apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zot

images:
# https://github.com/project-zot/zot/pkgs/container/zot
- name: ghcr.io/project-zot/zot
  newTag: v2.1.13 

resources:
- fetch-images.yaml