apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

images:
- name: redis
  newTag: 8.6.0-alpine 

labels:
  - pairs:
      app.kubernetes.io/instance: immich-redis
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: immich
    includeSelectors: true

resources:
- redis.yaml