apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

images:
- name: ghcr.io/damongolding/immich-kiosk
  newTag: "0.32.0"

labels:
  - pairs:
      app.kubernetes.io/instance: immich-kiosk
      app.kubernetes.io/name: immich-kiosk
      app.kubernetes.io/component: kiosk
      app.kubernetes.io/part-of: immich
    includeSelectors: true

configMapGenerator:
  - name: immich-kiosk-config
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true

resources:
- secrets.yaml
- deployment.yaml
- ingress.yaml
