apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

images:
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v2.5.2-rknn

labels:
  - pairs:
      app.kubernetes.io/instance: immich-machine-learning
      app.kubernetes.io/name: immich-machine-learning
      app.kubernetes.io/component: machine-learning
      app.kubernetes.io/part-of: immich
    includeSelectors: true

resources:
- deployment.yaml
