apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kopia

images:
- name: kopia/kopia
  newTag: 0.22.3
- name: ghcr.io/stephanme/toolbox
  newTag: latest

resources:
- secrets.yaml
- backup-nasbox.yaml
- backup-pi2.yaml
- backup-external.yaml
- usb-backup-watcher.yaml
