apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

images:
- name: ghcr.io/immich-app/immich-server
  newTag: v2.4.1

labels:
  - pairs:
      app.kubernetes.io/instance: immich-server
      app.kubernetes.io/name: immich-server
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: immich
    includeSelectors: true

resources:
- deployment.yaml
- ingress.yaml